version: '3.9'

services: 
  first-nginx: 
    image: nginx:latest
    container_name: first-nginx-container
    # ports:  All port should be access from the load balancer 
    #   - 9991:80   so no need to open port 
    volumes:
      - ./nginx/html/index1.html:/usr/share/nginx/html/index.html
    networks: 
      nginx-network: 
        ipv4_address: 192.168.0.10

  second-nginx: 
    image: nginx:latest
    container_name: second-nginx-container
    # ports: 
    #   - 9992:80
    volumes:
      - ./nginx/html/index2.html:/usr/share/nginx/html/index.html
    networks: 
      - nginx-network

  third-nginx: 
    image: nginx:latest
    container_name: third-nginx-container
    # ports: 
    #   - 9993:80
    volumes:
      - ./nginx/html/index3.html:/usr/share/nginx/html/index.html
    networks: 
      - nginx-network

  loadbalancer:
    image: nginx:latest
    container_name: loadbalancer-container
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 8888:80
    networks: 
      - nginx-network

networks: 
  nginx-network: 
    ipam: 
      driver: default 
      config: 
        - subnet: 192.168.0.0/24
          gateway: 192.168.0.1
